name: What do I have
on:
  push:
    branches: ["**"]

jobs:
  introspection:
    name: Introspection
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: introspect
      run: |
        ls -l
